# Generated by Django 5.2.3 on 2025-06-30 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_local', models.CharField(max_length=100)),
                ('equipo_visitante', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('resultado', models.CharField(choices=[('L', 'Local gana'), ('V', 'Visitante gana'), ('E', 'Empate'), ('P', 'Pendiente')], default='P', max_length=1)),
                ('relevante', models.BooleanField(default=False, help_text='Indica si el partido se muestra en la página de inicio')),
            ],
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('eleccion', models.CharField(choices=[('L', 'Gana local'), ('V', 'Gana visitante'), ('E', 'Empate')], max_length=1)),
                ('ganada', models.BooleanField(blank=True, null=True)),
                ('fecha_apuesta', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas', to=settings.AUTH_USER_MODEL)),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuestas', to='api.partido')),
            ],
        ),
    ]
